---
params: 
    title: ""
    StockPars: "`r list()`"
    plotPars: "`r list()`"
    tabs: "`r TRUE`"
    its: " `r numeric()`"
    nyears: " `r numeric()`"
    proyears: " `r numeric()`"
    date: "`r Sys.Date()`"
title: "`r params$title`"
date: "`r params$date`"
output:
  html_document
---


```{r, echo=FALSE, results="asis"}
if (params$tabs) {
  cat('## Growth Parameters {.tabset .tabset-fade .tabset-pills}' )
} else {
  cat('## Growth Parameters')
}

dd <- StockPars$M_ageArray %>% dim()
nsim <- dd[1]
maxage <- dd[2]

nsamp <- length(its)

# cat(paste0("\n\nNumber of simulations: ", nsim))
# cat(paste0("\n\nNumber of historical years: ", nyears))
# cat(paste0("\n\nNumber of projection years: ", proyears))
```

### Sampled Parameters 
Histograms of `r nsim` simulations of `Linf`, `Linfsd`, `K`, `Ksd`, and `t0` parameters, with vertical colored lines indicating `r nsamp` randomly drawn values used in other plots:

```{r, echo=FALSE}
par(mfrow=c(2,3))
hist2(StockPars$Linf, main="Linf", col=plotPars$col, axes=plotPars$axes,
      breaks=plotPars$breaks, cex.main=plotPars$cex.main)
abline(v=StockPars$Linf[its], col=1:nsamp, lwd=plotPars$lwd)
axis(side=1) 

hist2(StockPars$Linfsd, main="Linfsd", col=plotPars$col, axes=plotPars$axes,
      breaks=plotPars$breaks, cex.main=plotPars$cex.main)
abline(v=StockPars$Linfsd[its], col=1:nsamp, lwd=plotPars$lwd)
axis(side=1) 

hist2(StockPars$K, main="K", col=plotPars$col, axes=plotPars$axes,
      breaks=plotPars$breaks, cex.main=plotPars$cex.main)
abline(v=StockPars$K[its], col=1:nsamp, lwd=plotPars$lwd)
axis(side=1) 

hist2(StockPars$Ksd, main="Ksd", col=plotPars$col, axes=plotPars$axes,
      breaks=plotPars$breaks, cex.main=plotPars$cex.main)
abline(v=StockPars$Ksd[its], col=1:nsamp, lwd=plotPars$lwd)
axis(side=1)

hist2(StockPars$t0, main="t0", col=plotPars$col, axes=plotPars$axes,
      breaks=plotPars$breaks, cex.main=plotPars$cex.main)
abline(v=StockPars$t0[its], col=1:nsamp, lwd=plotPars$lwd)
axis(side=1) 

```

### Time-Series

```{r, echo=FALSE}
matplot(t(StockPars$Linfarray[its,]), type="l", bty="l", main="Linf by Year", lwd=plotPars$lwd, lty=1)
matplot(t(StockPars$Karray[its,]), type="l", bty="l", main="K by Year", lwd=plotPars$lwd, lty=1)
```



### Growth Curves


