---
params: 
    title: ""
    Pars: "`r list()`"
    plotPars: "`r list()`"
    tabs: "`r TRUE`"
    its: " `r numeric()`"
    nyears: " `r numeric()`"
    proyears: " `r numeric()`"
    date: "`r Sys.Date()`"
title: "`r params$title`"
date: "`r params$date`"
output:
  html_document
---


```{r, echo=FALSE, results="asis"}
if (params$tabs) {
  cat('## Recruitment Parameters {.tabset .tabset-fade .tabset-pills}' )
} else {
  cat('## Recruitment Parameters')
}

dd <- Pars$M_ageArray %>% dim()
nsim <- dd[1]
maxage <- dd[2]

nsamp <- length(its)

if (Pars$SRrel[1] == 1) SR <- "Beverton-Holt"
if (Pars$SRrel[1] == 2) SR <- "Ricker"

```

### Sampled Parameters 
Histograms of `r nsim` simulations of steepness (`h`), recruitment process error (`Perr`) and auto-correlation (`AC`) for the `r SR` stock-recruitment relationship, with vertical colored lines indicating `r nsamp` randomly drawn values used in other plots:

```{r, echo=FALSE}
par(mfrow=c(2,3))
hist2(Pars$hs, col=col, axes=plotPars$axes, main="Steepness (h)", breaks=plotPars$breaks)
abline(v=Pars$hs[its], col=1:nsamp, lwd=plotPars$lwd)
axis(side=1)  

hist2(Pars$procsd, col=col, axes=plotPars$axes, main="Recruitment process error (Perr)", breaks=plotPars$breaks)
abline(v=Pars$procsd[its], col=1:nsamp, lwd=plotPars$lwd)
axis(side=1) 

hist2(Pars$AC, col=col, axes=plotPars$axes, main="Auto-correlation (AC)", breaks=plotPars$breaks)
abline(v=Pars$AC[its], col=1:nsamp, lwd=plotPars$lwd)
axis(side=1)

```

### Time-Series

```{r, echo=FALSE}
matplot(t(Pars$Perr_y[its,]), type="l", bty="l", main="Rec Devs by Year", lwd=plotPars$lwd, lty=1)
```

