---
title: "OMx"
author: "Adrian H"
date: "January 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# OMx 


## Biological Reference Points

SB0 and B0 are calculated dynamically - every year given that years life-history parameters

Recruitment parameters are calculated from the unfished spawning-stock-per-recruit averaged over the first 10 years

Unfished biological reference points used to calculate depletion are calculated from average 10 years around last historical year - 
i.e mean(N0[(nyears-5):(nyears+4)]). Unless proyears < 4

SSB0 used for *both* initial and current depletion is calculated from average SB0 from today's conditions and for future projections - ie Data@Dep is calculated as spawning biomass divided
by expected unfished spawning biomass in last historical year


MSY reference points are calculated from the same reference years - 10 years around current year 
Selectivity is averaged over recent 10 years

MSY is calculated assuming that all fish that suffer fishing mortality are retained by the fishery - ie if there is a large degree of discarding, actual catches will be < MSY 
even if F is exactly FMSY

Reference yield - calculate by projecting population forward from its current state (last historical year) and optimizing for highest yield from a fixed F policy


Check effort calculations - with spatial closures, constant effort, constant catch
add change in catchability to effort calculation?

run checks for Effort controls 

Survey is taken mid-year, before fishing occurs

Maximum age - remove slot and replace with general assumption - not done - used for M-at-age


Hist object - document



