# This file is auto-generated by DLMtool_build/Roxygen-write.R
# Do not edit by hand


#' @slot Name Name of the Fleet object. Single value. Character string.
#' @slot nyears The number of years for the historical 'spool-up' simulation.
#'  Single value. Positive integer
#' @slot CurrentYr The current calendar year (final year) of the historical
#'  simulations (eg 2011). Single value. Positive integer
#' @slot EffYears Years representing join-points (vertices) of time-varying
#'  effort. Vector. Non-negative real numbers
#' @slot EffLower Lower bound on relative effort corresponding to EffYears.
#'  Vector. Non-negative real numbers
#' @slot EffUpper Upper bound on relative effort corresponding to EffYears.
#'  Vector. Non-negative real numbers
#' @slot Esd Additional inter-annual variability in fishing mortality rate.
#'  Uniform distribution lower and upper bounds. Non-negative real numbers
#' @slot qinc Average percentage change in fishing efficiency (applicable only
#'  to forward projection and input controls). Uniform distribution lower and upper
#'  bounds. Non-negative real numbers
#' @slot qcv Inter-annual variability in fishing efficiency (applicable only to
#'  forward projection and input controls). Uniform distribution lower and upper
#'  bounds. Non-negative real numbers
#' @slot L5 Shortest length corresponding to 5 percent vulnerability. Uniform
#'  distribution lower and upper bounds. Positive real numbers
#' @slot LFS Shortest length that is fully vulnerable to fishing. Uniform
#'  distribution lower and upper bounds. Positive real numbers
#' @slot Vmaxlen The vulnerability of fish at \code{Stock@Linf}. Uniform
#'  distribution lower and upper bounds. Fraction
#' @slot isRel Selectivity parameters in units of size-of-maturity (or absolute
#'  eg cm). Single value. Boolean
#' @slot LR5 Shortest length corresponding ot 5 percent retention. Uniform
#'  distribution lower and upper bounds. Non-negative real numbers
#' @slot LFR Shortest length that is fully retained. Uniform distribution lower
#'  and upper bounds. Non-negative real numbers
#' @slot Rmaxlen The retention of fish at \code{Stock@Linf}. Uniform
#'  distribution lower and upper bounds. Non-negative real numbers
#' @slot DR Discard rate - the fraction of caught fish that are discarded.
#'  Uniform distribution lower and upper bounds. Fraction
#' @slot Spat_targ Distribution of fishing in relation to spatial biomass:
#'  fishing distribution is proportional to B^Spat_targ. Uniform distribution lower
#'  and upper bounds. Real numbers
