
# Title
Include name and location of the Fishery. One line only.

# Subtitle
Subtitle. One line only.

# Author(s)
Name and contact details (e.g email, affiliation) for each author.
One line per author.

# Date
Optional. Date that the operating model was created. If none provided, today's date will be used.

# Introduction

## Completing the OM Documentation
This document is used to generate a HTML OM report document.

The document is separated into 7 sections:
1. Introduction (this section)
2. Custom Parameters (optional)
3. Stock Parameters
4. Fleet Parameters
5. Obs (Observation) Parameters
6. Imp (Implementation) Parameters
7. References

The Introduction section is used to briefly describe the fishery and the details of the Operating Model.
It should include an explanation for the OM parameters:
 * nsim: the number of simulations.
 * proyears: the number of projectio years.
 * interval: the management interval.
 * pstar: the percentile of the sample of the management recommendation for each method.
 * maxF: the maximum instantaneous fishing mortality rate that may be simulated for any given age class.
 * reps: the number of samples of the management recommendation for each method.

The Custom Parameters section is optional and should only be included if the cpars feature of DLMtool is used in the OM.
Delete both the heading and the text in this section if `cpars` are not used.

The Stock, Fleet, Obs, and Imp sections include each slot in these components of the OM object.
Provide details (including references where applicable) for the choice of values for each slot below the corresponding slot name (e.g., ## M).
For example: 
**M**
An explanation for the values of the natural mortality rate in the OM (Smith et al. 1999).

You do not need to include the actual values from the OM. These will be included automatically in the final compiled document.

References should be included in the 'References' section at the end of the document.

Once complete, this text file will be compiled into an OM Report Document.
This text file is linked to the Excel spreadsheet that was generated with the same file name.
It serves as a single documentation source for a DLMtool OM, and should be updated whenever parameter values in the OM spreadsheet are updated.

## Tips on filling this Document

This document is uses the Markdown format. All first and second level headings have been provided, and in general you
should only need to enter plain text.

You can have multiple paragraphs throughout the document.

The Introduction and Custom Parameters sections also support second and third level headings.

## An example Second level heading

### An example third level heading

### Technical Tip

This document will be compiled into Rmarkdown, and then a HTML document using Pandoc. Equations can be included by

using Latex (see [here](https://www.sharelatex.com/learn/Mathematical_expressions) for some examples).

## Replace all text below 'Introduction' new text.



# Custom Parameters
Optional. Only required if the `cpars` feature is used in the OM.

Provide details for the parameters included in 'cpars' here instead of in the corresponding slot sections below.
Text in the slot section below will be ignored if a parameter is included in 'cpars'.
Delete this section (including heading) if the `cpars` feature is not used in the OM.


# Stock Parameters

## Common_Name
No justification provided. 

## maxage
No justification provided. 

## R0
No justification provided. 

## M
No justification provided. 

## M2
No justification provided. 

## Mexp
No justification provided. 

## Msd
No justification provided. 

## h
No justification provided. 

## SRrel
No justification provided. 

## Perr
No justification provided. 

## AC
No justification provided. 

## Period
No justification provided. 

## Amplitude
No justification provided. 

## Linf
No justification provided. 

## K
No justification provided. 

## t0
No justification provided. 

## LenCV
No justification provided. 

## Ksd
No justification provided. 

## Linfsd
No justification provided. 

## L50
No justification provided. 

## L50_95
No justification provided. 

## D
No justification provided. 

## a
No justification provided. 

## b
No justification provided. 

## Size_area_1
No justification provided. 

## Frac_area_1
No justification provided. 

## Prob_staying
No justification provided. 

## Fdisc
No justification provided. 

## Source
No justification provided. 



# Fleet Parameters

## nyears
No justification provided. 

## Spat_targ
No justification provided. 

## EffYears
No justification provided. 

## EffLower
No justification provided. 

## EffUpper
No justification provided. 

## Esd
No justification provided. 

## qinc
No justification provided. 

## qcv
No justification provided. 

## L5
No justification provided. 

## LFS
No justification provided. 

## Vmaxlen
No justification provided. 

## isRel
No justification provided. 

## LR5
No justification provided. 

## LFR
No justification provided. 

## Rmaxlen
No justification provided. 

## DR
No justification provided. 

## SelYears
No justification provided. 

## AbsSelYears
No justification provided. 

## L5Lower
No justification provided. 

## L5Upper
No justification provided. 

## LFSLower
No justification provided. 

## LFSUpper
No justification provided. 

## VmaxLower
No justification provided. 

## VmaxUpper
No justification provided. 

## CurrentYr
No justification provided. 

## MPA
No justification provided. 



# Obs Parameters

## Cobs
No justification provided. 

## Cbiascv
No justification provided. 

## CAA_nsamp
No justification provided. 

## CAA_ESS
No justification provided. 

## CAL_nsamp
No justification provided. 

## CAL_ESS
No justification provided. 

## Iobs
No justification provided. 

## Ibiascv
No justification provided. 

## Btobs
No justification provided. 

## Btbiascv
No justification provided. 

## beta
No justification provided. 

## LenMbiascv
No justification provided. 

## Mbiascv
No justification provided. 

## Kbiascv
No justification provided. 

## t0biascv
No justification provided. 

## Linfbiascv
No justification provided. 

## LFCbiascv
No justification provided. 

## LFSbiascv
No justification provided. 

## FMSYbiascv
No justification provided. 

## FMSY_Mbiascv
No justification provided. 

## BMSY_B0biascv
No justification provided. 

## Irefbiascv
No justification provided. 

## Brefbiascv
No justification provided. 

## Crefbiascv
No justification provided. 

## Dbiascv
No justification provided. 

## Dobs
No justification provided. 

## hbiascv
No justification provided. 

## Recbiascv
No justification provided. 



# Imp Parameters

## TACFrac
No justification provided. 

## TACSD
No justification provided. 

## TAEFrac
No justification provided. 

## TAESD
No justification provided. 

## SizeLimFrac
No justification provided. 

## SizeLimSD
No justification provided. 



# References

