# 
# setwd("C:/Users/Adrian/Dropbox/Projects_2019/tRFMOs/Data/SKJ_WCPO/SKJ_2016_basecase")
# 
# plot.rep <- "plot-11.par.rep"
# 
# nsim = 48; proyears = 50; reps = 1; maxF = 3; seed = 1; 
# Obs = DLMtool::Generic_Obs; Imp = DLMtool::Perfect_Imp
# Name = "OM generated by SS2OM function"; Source = "No source provided"; Author = "No author provided"

MultiCL2OM <- function(nsim = 48, proyears = 50, reps = 1, maxF = 3, 
                       seed = 1, Obs = DLMtool::Generic_Obs, Imp = DLMtool::Perfect_Imp,
                       Name = "OM generated by SS2OM function", 
                       Source = "No source provided", Author = "No author provided") {
  
  
  # Create OM object
  Stock <- new("Stock")
  Fleet <- new("Fleet")
  OM <- new("OM", Stock = Stock, Fleet = Fleet, Obs = Obs, Imp = Imp)
  OM@nsim <- nsim
  OM@proyears <- proyears
  OM@Name <- Name
  OM@Source <- paste0(Source, ". Author: ", Author, ".")
  OM@maxF <- maxF
  OM@reps <- reps
  OM@seed <- seed
  
  datain <- readLines(plot.rep)
  

# Stock Parameters --------------------------------------------------------

  
  # Natural Mortality at Age
  M_at_age <- datain[which(grepl("Natural mortality at age", datain))+1] %>% strsplit(" ") %>%
    unlist() %>% trimws()
  M_at_age <- M_at_age[nchar(M_at_age)>0] %>% as.numeric()
  OM@maxage <- length(M_at_age)
  OM@M <- M_at_age
  OM@M2 <- M_at_age + tiny
  OM@Msd <- c(0,0)
    
  # Recruitment
  ind <- grepl("# Beverton-Holt stock-recruitment relationship report", datain, fixed=TRUE) %>% which()
  BHSRRtext <- scan(text=datain[ind+1], what='character')
  OM@h <- rep(BHSRRtext[which(grepl("steepness", BHSRRtext))+2] %>% as.numeric(),2)
  OM@R0 <- BHSRRtext[which(grepl("alpha", BHSRRtext))+2] %>% as.numeric()
  if (OM@R0 > 1E6) OM@R0 <- OM@R0/1E6
  
  OM@SRrel <- 1
  OM@Perr <- BHSRRtext[which(grepl("variance", BHSRRtext))+2] %>% as.numeric() %>% sqrt()
  message('Skipping AC for now...')
  OM@AC <- c(0,0)
  
  # Growth 
  ind <- grepl("# Mean lengths at age", datain, fixed=TRUE) %>% which()
  Len_age <- scan(text=datain[ind+1], what='numeric') %>% as.numeric()
  Len_age <- matrix(Len_age, nrow=OM@nsim, ncol=OM@maxage, byrow=TRUE)
  Len_age <- replicate(OM@nyears+OM@proyears, Len_age)
  OM@cpars$Len_age <- Len_age
  
  ind <- grepl("# SD of length at age", datain, fixed=TRUE) %>% which()
  LatASD <- scan(text=datain[ind+1], what='numeric') %>% as.numeric()
  LatASD <- matrix(LatASD, nrow=OM@nsim, ncol=OM@maxage, byrow=TRUE)
  LatASD <- replicate(OM@nyears+OM@proyears, LatASD)
  OM@cpars$Len_age <- Len_age
  
  ind <- grepl("# Mean weights at age", datain, fixed=TRUE) %>% which()
  Wt_age <- scan(text=datain[ind+1], what='numeric') %>% as.numeric()
  Wt_age <- matrix(Wt_age, nrow=OM@nsim, ncol=OM@maxage, byrow=TRUE)
  Wt_age <- replicate(OM@nyears+OM@proyears, Wt_age)
  OM@cpars$Wt_age <- Wt_age
  

  
  # Selectivity
  ind <- grepl("# Selectivity by age class (across) and fishery (down)", datain, fixed=TRUE) %>% which()
  ind2 <- grepl("# length bin mid-points", datain, fixed=TRUE) %>% which()
  
  Select_Fleets <- matrix(scan(text = datain[(ind+1):(ind2-1)]), ncol=OM@maxage, byrow = TRUE)
  
 
  # Historical Fishing Mortality 
  ind <- grepl("# Fishing mortality by age class (across) and year (down)", datain, fixed=TRUE) %>% which()
  ind2 <- grepl("# Fishing mortality by age class (across), year (down) and region (block)", datain, fixed=TRUE) %>% which()
 
  HistFs <- matrix(scan(text = datain[(ind+2):(ind2-1)]), ncol=OM@maxage, byrow = TRUE)
  nrow(HistFs)
  
  SB0 <- 6.764e+06

  
}
